namespace GenerativeAI.Types;

/// <summary>
/// Tool that executes code generated by the model, and automatically returns the result to the model.
/// See also <see cref="ExecutableCode"/> and <see cref="CodeExecutionResult"/> which are only generated when using this tool.
/// </summary>
/// <seealso href="https://ai.google.dev/api/caching#CodeExecution">See Official API Documentation</seealso>
public class CodeExecutionTool // Renamed to CodeExecutionTool
{
    // No properties as of the provided documentation
}