using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// Code generated by the model that is meant to be executed, and the result returned to the model.
/// Only generated when using the <see cref="CodeExecutionTool"/> tool, in which the code will be automatically
/// executed, and a corresponding <see cref="CodeExecutionResult"/> will also be generated.
/// </summary>
/// <seealso href="https://ai.google.dev/api/rest/v1beta/ExecutableCode">See Official API Documentation</seealso>
public class ExecutableCode
{
    /// <summary>
    /// Required. Programming language of the <c>code</c>.
    /// </summary>
    [JsonPropertyName("language")]
    public Language Language { get; set; }

    /// <summary>
    /// Required. The code to be executed.
    /// </summary>
    [JsonPropertyName("code")]
    public string Code { get; set; }
}