using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// Response message for the LiveMusicClientMessage call.
/// </summary>
public class LiveMusicServerMessage
{
    /// <summary>
    /// Message sent in response to a `LiveMusicClientSetup` message from the client.
    /// Clients should wait for this message before sending any additional messages.
    /// </summary>
    [JsonPropertyName("setupComplete")]
    public LiveMusicServerSetupComplete? SetupComplete { get; set; }

    /// <summary>
    /// Content generated by the model in response to client messages.
    /// </summary>
    [JsonPropertyName("serverContent")]
    public LiveMusicServerContent? ServerContent { get; set; }

    /// <summary>
    /// A prompt that was filtered with the reason.
    /// </summary>
    [JsonPropertyName("filteredPrompt")]
    public LiveMusicFilteredPrompt? FilteredPrompt { get; set; }
}
