using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// Server update generated by the model in response to client messages.
/// Content is generated as quickly as possible, and not in real time.
/// Clients may choose to buffer and play it out in real time.
/// </summary>
public class LiveMusicServerContent
{
    /// <summary>
    /// The audio chunks that the model has generated.
    /// </summary>
    [JsonPropertyName("audioChunks")]
    public List<AudioChunk>? AudioChunks { get; set; }
}
