namespace GenerativeAI.Types;

/// <summary>
/// Represents the safety filter level.
/// </summary>
/// <seealso href="https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/imagen-api">See Official API Documentation</seealso>
public enum ImageSafetySetting
{
    /// <summary>
    /// Strongest filtering level, most strict blocking.
    /// </summary>
    block_low_and_above,
    /// <summary>
    /// Block some problematic prompts and responses.
    /// </summary>
    block_medium_and_above,
    /// <summary>
    /// Reduces the number of requests blocked due to safety filters. May increase objectionable content generated by Imagen.
    /// </summary>
    block_only_high,
    /// <summary>
    /// Block very few problematic prompts and responses. Access to this feature is restricted.
    /// </summary>
    block_none
}