using System.Text.Json.Serialization;
using GenerativeAI.Types.Converters;

namespace GenerativeAI.Types;

/// <summary>
/// Defines the reason why the model stopped generating tokens.
/// </summary>
/// <remarks>
/// This enum uses a lenient JSON converter that gracefully handles unknown values
/// by falling back to <see cref="OTHER"/> instead of throwing an exception.
/// This prevents crashes when Google adds new FinishReason values to their API.
/// </remarks>
/// <seealso href="https://ai.google.dev/api/generate-content#FinishReason">See Official API Documentation</seealso>
[JsonConverter(typeof(LenientFinishReasonConverter))]
public enum FinishReason
{
    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    FINISH_REASON_UNSPECIFIED = 0,

    /// <summary>
    /// Natural stop point of the model or provided stop sequence.
    /// </summary>
    STOP = 1,

    /// <summary>
    /// The maximum number of tokens as specified in the request was reached.
    /// </summary>
    MAX_TOKENS = 2,

    /// <summary>
    /// The response candidate content was flagged for safety reasons.
    /// </summary>
    SAFETY = 3,

    /// <summary>
    /// The response candidate content was flagged for recitation reasons.
    /// </summary>
    RECITATION = 4,

    /// <summary>
    /// The response candidate content was flagged for using an unsupported language.
    /// </summary>
    LANGUAGE = 5,

    /// <summary>
    /// Unknown reason.
    /// </summary>
    OTHER = 6,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    BLOCKLIST = 7,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    PROHIBITED_CONTENT = 8,

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally
    /// Identifiable Information (SPII).
    /// </summary>
    SPII = 9,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    MALFORMED_FUNCTION_CALL = 10,

    /// <summary>
    /// Token generation stopped because generated images contain safety violations.
    /// </summary>
    IMAGE_SAFETY = 11,

    /// <summary>
    /// Token generation stopped due to model armor protection mechanisms.
    /// Documented in Vertex AI (google.cloud.aiplatform.v1).
    /// </summary>
    MODEL_ARMOR = 12,

    /// <summary>
    /// Image generation stopped because generated images have prohibited content.
    /// Documented in Vertex AI (google.cloud.aiplatform.v1).
    /// </summary>
    IMAGE_PROHIBITED_CONTENT = 13,

    /// <summary>
    /// Image generation stopped because generated images were flagged for recitation.
    /// Documented in Vertex AI (google.cloud.aiplatform.v1).
    /// </summary>
    IMAGE_RECITATION = 14,

    /// <summary>
    /// Image generation stopped because of other miscellaneous issues.
    /// Documented in Vertex AI (google.cloud.aiplatform.v1).
    /// </summary>
    IMAGE_OTHER = 15,

    /// <summary>
    /// Model generated a tool call but no tools were enabled in the request.
    /// Documented in Gemini API and Vertex AI.
    /// </summary>
    UNEXPECTED_TOOL_CALL = 16,

    /// <summary>
    /// The model was expected to generate an image, but none was generated.
    /// Documented in Vertex AI (google.cloud.aiplatform.v1).
    /// </summary>
    NO_IMAGE = 17,

    /// <summary>
    /// Model called too many tools consecutively, thus the system exited execution.
    /// Documented in generativelanguagepb (SDK/proto contract).
    /// </summary>
    TOO_MANY_TOOL_CALLS = 18,
}