using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// Defines the reason why the model stopped generating tokens.
/// </summary>
/// <seealso href="https://ai.google.dev/api/generate-content#FinishReason">See Official API Documentation</seealso>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FinishReason
{
    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    FINISH_REASON_UNSPECIFIED = 0,

    /// <summary>
    /// Natural stop point of the model or provided stop sequence.
    /// </summary>
    STOP = 1,

    /// <summary>
    /// The maximum number of tokens as specified in the request was reached.
    /// </summary>
    MAX_TOKENS = 2,

    /// <summary>
    /// The response candidate content was flagged for safety reasons.
    /// </summary>
    SAFETY = 3,

    /// <summary>
    /// The response candidate content was flagged for recitation reasons.
    /// </summary>
    RECITATION = 4,

    /// <summary>
    /// The response candidate content was flagged for using an unsupported language.
    /// </summary>
    LANGUAGE = 5,

    /// <summary>
    /// Unknown reason.
    /// </summary>
    OTHER = 6,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    BLOCKLIST = 7,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    PROHIBITED_CONTENT = 8,

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally
    /// Identifiable Information (SPII).
    /// </summary>
    SPII = 9,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    MALFORMED_FUNCTION_CALL = 10,

    /// <summary>
    /// Token generation stopped because generated images contain safety violations.
    /// </summary>
    IMAGE_SAFETY = 11,
}