using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace GenerativeAI.Tools
{
    public  class ChatFunctionCall
    {
        /// <summary>
        /// The name of the function to call.
        /// </summary>

        [JsonPropertyName("name")]

        [JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
        [Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
        /// </summary>

        [JsonPropertyName("args")]

        [JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
        [Required(AllowEmptyStrings = true)]
        public IDictionary<string, object>? Arguments { get; set; } = default!;

        private IDictionary<string, object>? _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }
    }
}
