using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// Source of the File.
/// </summary>
/// <seealso href="https://ai.google.dev/api/files#Source">See Official API Documentation</seealso>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Source
{
    /// <summary>
    /// Used if source is not specified.
    /// </summary>
    SOURCE_UNSPECIFIED = 0,

    /// <summary>
    /// Indicates the file is uploaded by the user.
    /// </summary>
    UPLOADED = 1,

    /// <summary>
    /// Indicates the file is generated by Google.
    /// </summary>
    GENERATED = 2,
}