using System.Text.Json.Serialization;

namespace GenerativeAI.Types;

/// <summary>
/// The reason why the turn is complete.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<TurnCompleteReason>))]
public enum TurnCompleteReason
{
    /// <summary>
    /// Default value. Reason is unspecified.
    /// </summary>
    TURN_COMPLETE_REASON_UNSPECIFIED = 0,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    MALFORMED_FUNCTION_CALL = 1,

    /// <summary>
    /// The response is rejected by the model.
    /// </summary>
    RESPONSE_REJECTED = 2,

    /// <summary>
    /// Needs more input from the user.
    /// </summary>
    NEED_MORE_INPUT = 3
}
